### ISSUE TITLE
IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable

### ISSUE THREAD

**Issue by TechnicJelle** [Lulonaut/AutoFetch#2]
Hi there! I love this plugin, it's super great and exactly what I wanted for ages! :D
Though recently, it's been giving errors...

```
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:127)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:125)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:94)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:125)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:120)
	at org.jetbrains.plugins.github.extensions.GHProtectedBranchRulesLoader.loadProtectionRules(GHProtectedBranchRulesLoader.kt:89)
	at org.jetbrains.plugins.github.extensions.GHProtectedBranchRulesLoader.doAfterSuccessfulFetch(GHProtectedBranchRulesLoader.kt:33)
	at git4idea.fetch.GitFetchHandler$Companion.afterSuccessfulFetch(GitFetchHandler.kt:16)
	at git4idea.fetch.GitFetchSupportImpl$fetch$1.invoke(GitFetchSupportImpl.kt:124)
	at git4idea.fetch.GitFetchSupportImpl$fetch$1.invoke(GitFetchSupportImpl.kt:109)
	at git4idea.fetch.GitFetchSupportImpl.withIndicator(GitFetchSupportImpl.kt:219)
	at git4idea.fetch.GitFetchSupportImpl.fetch(GitFetchSupportImpl.kt:109)
	at git4idea.fetch.GitFetchSupportImpl.fetchAllRemotes(GitFetchSupportImpl.kt:91)
	at de.lulonaut.autofetch.AutoFetch.lambda$runActivity$1(AutoFetch.java:38)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I think it happened after an IntelliJ update, but I'm not sure which one, exactly :sweat_smile:.
It happens on IntelliJ IDEA, Rider, and CLion, too.

**Comment by Lulonaut** [comment]
Hey, sorry to leave you waiting, I somehow did not get a notification for this issue.

I also noticed your issue and released an update which may fix it (I have not been getting any errors while testing).

JetBrains takes a few days to approve the update, but it should be out by Tuesday.

**Comment by Lulonaut** [comment]
After another fix I left it running with the delay set to 1 minute for over an hour now with no errors.

If you want, you can download the version [here](https://plugins.jetbrains.com/files/20464/412463/autofetch-1.6.jar) before JetBrains approves it.

This is the exact file that is currently pending review.

**Comment by TechnicJelle** [comment]
Wow, thank you so much!
I'll try to remember to give it a shot tomorrow, if I have time.
Will keep you posted!

**Comment by TechnicJelle** [comment]
I've got then update, and it seems to be working great again, now!
Thanks a bunch!!!
